app-service/connect-to-redis/connect-to-redis.sh

Somehow the --name and --resource-group values were cut off the final command, I'm adding those back.

replaced the missing properties

---

azure-functions/configure-custom-domain/configure-custom-domain.sh
azure-functions/configure-ssl-certificate/configure-ssl-certificate.sh

These still aren't test with the actual CLI, but I want to get the scripts in so that the wrapper docs will build.

Draft of Azure Functions CLI scripts

---

virtual-network/route-traffic-through-nva/route-traffic-through-nva.sh

Fixed this script to create two route tables for Frontend and Backend
subnets rather than one table associated to DMZ subnet.

Fixed Route tables associate to FE & BE subnets

---

app-service/configure-ssl-certificate/configure-ssl-certificate.sh

Signed-off-by: Robbie Page <rob@rorpage.com>

swap resource group to a var and fix thumbprint typo

---

mysql/server-logs/delete-mysql.sh
mysql/server-logs/server-logs.sh

@v-chenyh This is for your sample.

MySQL server logs samples

---

virtual-machine/encrypt-disks/encrypt_windows_vm.sh

Correcting resource group name in command example

VM encrypt - Windows

---

virtual-machine-scale-sets/create-single-availability-zone/create-single-availability-zone.sh

This sample script creates a simple VMSS in a single Availability Zone. The Custom Script Extension is then used to install a basic Nginx web server.

Adding VMSS single AZ script

---

mysql/create-mysql-server-vnet/create-mysql-server.sh
postgresql/create-postgresql-server-vnet/create-postgresql-server.sh

Basic servers are not supported in private preview. Need to create standard. Will edit these for basic when basic is supported

Create standard servers for Vnet private preview

---

media-services/media-services-create-account/Create-Account.sh

fixes MicrosoftDocs/azure-docs#13231

fixes MicrosoftDocs/azure-docs#13231

---

cosmosdb/create-cosmosdb-account-database/create-cosmosdb-account-database.sh
cosmosdb/create-cosmosdb-cassandra-account/create-cosmosdb-cassandra-account.sh
cosmosdb/create-cosmosdb-graph-account/create-cosmosdb-graph-account.sh
cosmosdb/create-cosmosdb-gremlin-account/create-cosmosdb-gremlin-account.sh
cosmosdb/create-cosmosdb-mongodb-account/create-cosmosdb-mongodb-account.sh
cosmosdb/create-cosmosdb-table-account/create-cosmosdb-table-account.sh
cosmosdb/high-availability-cosmosdb-configure-failover/high-availability-cosmosdb-configure-failover.sh
cosmosdb/scale-cosmosdb-get-account-key/secure-cosmosdb-get-account-key.sh
cosmosdb/scale-cosmosdb-replicate-multiple-regions/scale-cosmosdb-replicate-multiple-regions.sh
cosmosdb/scale-cosmosdb-throughput/scale-cosmosdb-throughput.sh
cosmosdb/secure-cosmosdb-create-firewall/secure-cosmosdb-create-firewall.sh
cosmosdb/secure-cosmosdb-get-mongodb-connection-string/secure-cosmosdb-get-mongodb-connection-string.sh
cosmosdb/secure-cosmosdb-regenerate-keys/secure-cosmosdb-regenerate-keys.sh

Updating all of the Cosmos DB CLI sample scripts.
@SnehaGunda, please review and merge if no issues.

Updates to all cosmos db CLI script samples

---

disk-encryption/prereq/prereq.sh

Fixed some issues with prereq.sh
This protects inner characters.
This makes nesting of substitutions easier.

Fix up prereq.sh

---

azure-signalr/create-signalr-service-and-group/create-signalr-service-and-group.sh
azure-signalr/create-signalr-with-app-service-github-oauth/create-signalr-with-app-service-github-oauth.sh
azure-signalr/create-signalr-with-app-service/create-signalr-with-app-service.sh

The current scripts for Azure SignalR are out-of-date.

Update Azure CLI scripts for Azure SignalR

---

cosmosdb/create-cosmosdb-mongodb-account/create-cosmosdb-mongodb-account.sh

Adding container creation

---

virtual-machine/copy-managed-disks-vhd-to-storage-account/copy-managed-disks-vhd-to-storage-account.sh

Related to this customer's issue in GitHub: https://github.com/MicrosoftDocs/azure-docs/issues/29614

Adding file extension to the script

---

.github/pull_request_template.md

Links updated contributor guides in the PR template.
N/A

Link contributor guides in template

---

sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh

this was retested on Bash with Linux

added missing parameter

---

cosmosdb/cassandra/create.sh
cosmosdb/cassandra/throughput.sh
cosmosdb/common/ipfirewall.sh
cosmosdb/common/keys.sh
cosmosdb/common/regions.sh
cosmosdb/common/service-endpoints-ignore-missing-vnet.sh
cosmosdb/common/service-endpoints.sh
cosmosdb/gremlin/create.sh
cosmosdb/gremlin/throughput.sh
cosmosdb/mongodb/create.sh
cosmosdb/mongodb/throughput.sh
cosmosdb/sql/create.sh
cosmosdb/sql/throughput.sh
cosmosdb/table/create.sh
cosmosdb/table/throughput.sh

Major update to cosmosdb cli. Now includes full support across all cosmos APIs. This PR is additions only. No existing samples are impacted. Once this PR is merged and docs have been updated, will submit another PR to clean out the outdated cli samples.
CLI version: 2.0.71
N/A

New cosmosdb cli samples

---

batch/render-scene/json/myrendertask.json

Resolves an error when running this using the CLI. It seems the schema has changed since this file was originally authored.
CLI version:
```
az --version
```

Update to use 'httpUrl' in place of 'blobSource'

---

azure-signalr/create-signalr-service-and-group/create-signalr-service-and-group.sh
azure-signalr/create-signalr-with-app-service-github-oauth/create-signalr-with-app-service-github-oauth.sh
azure-signalr/create-signalr-with-app-service/create-signalr-with-app-service.sh

Update SignalR Create command to use newer Sku and serviceMode. The old Sku is unrecommended for a while.
CLI version:
```
az --version
```

Update SignalR Create command to use newer Sku and serviceMode

---

app-service/integrate-with-app-gateway/integrate-with-app-gateway.sh

Script to create an deployment of Application Gateway integrated with App Service Web App using service endpoint and access restriction. 
To be referenced from Docs.
CLI version: 2.0.74
```
az --version
```

App Service integration with App Gateway

---

azure-functions/create-function-app-consumption-python/create-function-app-consumption-python.sh
azure-functions/create-function-app-premium-plan/create-function-app-premium-plan.sh

Added new CLI samples for Python function app and Premium plan
**CLI version:**  2.0.77
```
az --version
```
**Extensions required:**
None

Python function app and Premium plan

---

managed-applications/create-definition/create-definition.sh

Resolves MicrosoftDocs/azure-docs#43619
CLI version:
```
az --version
```

(AzureCXP) Updated package-file-uri

---

sql-database/copy-database-to-new-server/copy-database-to-new-server.sh
sql-database/database-auditing-and-threat-detection/database-auditing-and-threat-detection.sh
sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh
sql-database/failover-groups/add-managed-instance-to-failover-group-az-cli.sh
sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh
sql-database/import-from-bacpac/import-from-bacpac.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-database-failover-group.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-elastic-pool.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-single-database.sh
sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.sh

more scripts for powershell to cli equivalence

cli equivalent scripts

---

azure-functions/create-function-app-app-service-plan/create-function-app-app-service-plan.sh
azure-functions/create-function-app-connect-to-cosmos-db/create-function-app-connect-to-cosmos-db.sh
azure-functions/create-function-app-connect-to-storage/create-function-app-connect-to-storage-account.sh
azure-functions/create-function-app-consumption-python/create-function-app-consumption-python.sh
azure-functions/create-function-app-consumption/create-function-app-consumption.sh
azure-functions/create-function-app-premium-plan/create-function-app-premium-plan.sh
azure-functions/deploy-function-app-with-function-github-continuous/deploy-function-app-with-function-github-continuous.sh
azure-functions/deploy-function-app-with-function-github/deploy-function-app-with-function-github.sh
azure-functions/deploy-function-app-with-function-vsts/deploy-function-app-with-function-vsts.sh
azure-functions/functions-cli-mount-files-storage-linux/functions-cli-mount-files-storage-linux.sh

Add a new Linux consumption file share mount example
CLI version:
```
latest cloud shell
```

Add Python mount share example

---

sql-database/backup-database/backup-database.sh
sql-database/copy-database-to-new-server/copy-database-to-new-server.sh
sql-database/create-and-configure-database/create-and-configure-database.sh
sql-database/database-auditing-and-threat-detection/database-auditing-and-threat-detection.sh
sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh
sql-database/failover-groups/add-managed-instance-to-failover-group-az-cli.sh
sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh
sql-database/import-from-bacpac/import-from-bacpac.sh
sql-database/managed-instance/create-managed-instance.sh
sql-database/monitor-and-scale-database/monitor-and-scale-database.sh
sql-database/move-database-between-pools/move-database-between-pools.sh
sql-database/restore-database/restore-database.sh
sql-database/scale-pool/scale-pool.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-database-failover-group.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-elastic-pool.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-single-database.sh
sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.sh

Wrapping up work item, https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1566587/.

set of revisions

---

virtual-machine/copy-snapshots-to-storage-account/copy-snapshots-to-storage-account.sh

Masking the subscription ID, this script is being used https://docs.microsoft.com/en-us/azure/virtual-machines/scripts/virtual-machines-windows-cli-sample-copy-snapshot-to-storage-account#sample-script
CLI version:
```
az --version
```
azure-cli                          2.2.0
command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
appconfig                          0.5.0
Python location '/opt/az/bin/python3'
Extensions directory '/home/bharath/.azure/cliextensions'
Python (Linux) 3.6.5 (default, Mar  6 2020, 14:41:35)
[GCC 5.4.0 20160609]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

(AzureCXP) Masking the SubscriptionID

---

batch/add-application/add-application.sh

Updating the sample used by Docs [here](https://docs.microsoft.com/en-us/azure/batch/scripts/batch-cli-sample-add-application) due to MicrosoftDocs/azure-docs#44562.
CLI version:
```
az --version
```

Updating sample with current az batch parameters

---

cosmosdb/common/regions.sh

- Small fix to regional failover script

fix failover script

---

cosmosdb/cassandra/create.sh
cosmosdb/cassandra/throughput.sh
cosmosdb/common/regions.sh
cosmosdb/gremlin/create.sh
cosmosdb/gremlin/throughput.sh
cosmosdb/mongodb/create.sh
cosmosdb/mongodb/throughput.sh
cosmosdb/sql/create.sh
cosmosdb/sql/throughput.sh
cosmosdb/table/create.sh
cosmosdb/table/throughput.sh

fix incorrect /bin/bash statement

---

sql-database/move-database-between-pools/move-database-between-pools.sh

Gen4 is no longer a valid value so updating to use gen5.
I just successfully ran this in the portal cloud shell. 
CLI version:
```
az --version
```
2.8.0

sqldb - update from gen4 to gen5

---

cosmosdb/cassandra/autoscale.sh
cosmosdb/cassandra/create.sh
cosmosdb/cassandra/lock.sh
cosmosdb/cassandra/throughput.sh
cosmosdb/common/ipfirewall.sh
cosmosdb/common/keys.sh
cosmosdb/common/regions.sh
cosmosdb/common/service-endpoints-ignore-missing-vnet.sh
cosmosdb/common/service-endpoints.sh
cosmosdb/gremlin/autoscale.sh
cosmosdb/gremlin/create.sh
cosmosdb/gremlin/lock.sh
cosmosdb/gremlin/throughput.sh
cosmosdb/mongodb/autoscale.sh
cosmosdb/mongodb/create.sh
cosmosdb/mongodb/lock.sh
cosmosdb/mongodb/throughput.sh
cosmosdb/sql/autoscale.sh
cosmosdb/sql/create.sh
cosmosdb/sql/lock.sh
cosmosdb/sql/throughput.sh
cosmosdb/table/autoscale.sh
cosmosdb/table/create.sh
cosmosdb/table/lock.sh
cosmosdb/table/throughput.sh

- Added throughput migration between standard and autoscale throughput
- Added headers in each sample to point to az cli docs
- Cleaned up a few samples
azure-cli                         2.12.1

added ru migration and headers to all samples

---

storage/rotate-storage-account-keys/rotate-storage-account-keys.sh

Fix script to create storage account
- [ x] Scripts in this pull request are written for the `bash` shell.
- [ x] This pull request was tested on __at least one of__ the following platforms:
- [ x] Azure Cloud Shell
- [ x] Scripts do not contain passwords or other secret tokens.
- [ x] No deprecated commands or arguments are used. ([Release notes](https://docs.microsoft.com/cli/azure/release-notes-azure-cli))
- [ x] All Azure resource identifiers which must be universally unique are guaranteed to be so.
CLI version: 2.12.1
```
az --version
```
Extensions required: None

updating script to create storage acct

---

cosmosdb/cassandra/autoscale.sh
cosmosdb/cassandra/create.sh
cosmosdb/cassandra/throughput.sh
cosmosdb/common/ipfirewall.sh
cosmosdb/common/keys.sh
cosmosdb/common/regions.sh
cosmosdb/common/service-endpoints-ignore-missing-vnet.sh
cosmosdb/common/service-endpoints.sh
cosmosdb/gremlin/autoscale.sh
cosmosdb/gremlin/create.sh
cosmosdb/gremlin/throughput.sh
cosmosdb/mongodb/autoscale.sh
cosmosdb/mongodb/create.sh
cosmosdb/mongodb/throughput.sh
cosmosdb/sql/autoscale.sh
cosmosdb/sql/create.sh
cosmosdb/sql/throughput.sh
cosmosdb/table/autoscale.sh
cosmosdb/table/create.sh
cosmosdb/table/throughput.sh

Bulk update to fix variable for uniqueId for these scripts. Same update in each script.
CLI version:
```
az --version
``` 2.91

bulk update fix uniqueId variable

---

azure-front-door/deploy-custom-domain/README.md
azure-front-door/deploy-custom-domain/deploy-custom-apex-domain.sh
azure-front-door/deploy-custom-domain/deploy-custom-domain.sh
azure-front-door/deploy-custom-domain/index.html

Adds two sample scripts that add custom domains (sub-domains and apex domains) to Azure Front Door.
This script requires a custom domain name to be registered beforehand by the user and will fail if this has not been done. Pre-requisites are listed in the comments and a README with more information is provided.
This is my first contribution so please let me know if there is anything else I need to do.
CLI version:
```
az --version
azure-cli                         2.21.0
core                              2.21.0
telemetry                          1.0.6
Extensions:
front-door                        1.0.13
Python location '/opt/az/bin/python3'
Extensions directory '/home/dalars/.azure/cliextensions'
Python (Linux) 3.6.10 (default, Mar 19 2021, 05:58:22) 
[GCC 9.3.0]
``` …

Adds scripts for custom domain names in Azure Front Door

---

container-registry/service-principal-create/service-principal-create.sh

Service principal creation commands used in this script were updated due to change in `az ad ap create-for-rbac` introduced in CLI v 2.25.0: 
--name is now only used as the displayName of the app. It is not used to generate identifierUris
CLI version: 2.25.0
```
az --version
```
Extensions required: None

[ACR] Updated SP creation script

---

batch/create-account/create-account-user-subscription.sh

Updated code snippet
CLI version:
```
az --version
```

(Azure CXP) resolves MicrosoftDocs/azure-docs#80342

---

mysql/flexible-server/backup-restore/clean-up-resources.sh
mysql/flexible-server/backup-restore/restore-server.sh
mysql/flexible-server/configure-logs/clean-up-resources.sh
mysql/flexible-server/configure-logs/configure-audit-logs.sh
mysql/flexible-server/configure-logs/configure-slow-query-logs.sh
mysql/flexible-server/create-server-private-access/clean-up-resources.sh
mysql/flexible-server/create-server-private-access/create-connect-server-in-vnet.sh
mysql/flexible-server/create-server-public-access/clean-up-resources.sh
mysql/flexible-server/create-server-public-access/create-connect-burstable-server-public-access.sh
mysql/flexible-server/create-server-public-access/create-connect-gp-server-public-access.sh
mysql/flexible-server/high-availability/clean-up-resources.sh
mysql/flexible-server/high-availability/same-zone-ha.sh
mysql/flexible-server/high-availability/zone-redundant-ha.sh
mysql/flexible-server/manage-server/change-server-parameters.sh
mysql/flexible-server/manage-server/clean-up-resources.sh
mysql/flexible-server/manage-server/restart-start-stop.sh
mysql/flexible-server/monitor-and-scale/clean-up-resources.sh
mysql/flexible-server/monitor-and-scale/monitor-and-scale.sh
mysql/flexible-server/read-replicas/clean-up-resources.sh
mysql/flexible-server/read-replicas/create-manage-read-replicas.sh

Add Azure CLI sample scripts for Azure Database for MySQL - Flexible Server, under mysql/flexible-server. 
CLI version:
```
az --version
```
Extensions required: N/A

Add Azure CLI sample scripts for Azure Database for MySQL Flexible Server

---

sql-database/backup-database/backup-database.sh
sql-database/copy-database-to-new-server/copy-database-to-new-server.sh
sql-database/create-and-configure-database/create-and-configure-database.sh
sql-database/database-auditing-and-threat-detection/database-auditing-and-threat-detection.sh
sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh
sql-database/failover-groups/add-managed-instance-to-failover-group-az-cli.sh
sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh
sql-database/import-from-bacpac/import-from-bacpac.sh
sql-database/managed-instance/create-managed-instance.sh
sql-database/monitor-and-scale-database/monitor-and-scale-database.sh
sql-database/move-database-between-pools/move-database-between-pools.sh
sql-database/restore-database/restore-database.sh
sql-database/scale-pool/scale-pool.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-database-failover-group.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-elastic-pool.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-single-database.sh
sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.sh

CLI version:
```
az --version
```

Refreshed Azure SQL CLI scripts

---

sql-database/sql-managed-instance-restore-geo-backup/sql-managed-instance-restore-geo-backup-cli.sh
sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.sh

CLI version:
```
az --version
```

updated script and added script

---

sql-database/managed-instance/create-managed-instance.sh
sql-database/restore-database/restore-database.sh
sql-database/sql-managed-instance-restore-geo-backup/restore-geo-backup-cli.sh
sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.sh

CLI version:
```
az --version
```

final minor edits re: spaces

---

sql-database/create-and-configure-database/create-and-configure-database.sh

CLI version:
```
az --version
```

reorder lines of code

---

sql-database/backup-database/backup-database.sh
sql-database/create-and-configure-database/create-and-configure-database.sh
sql-database/database-auditing-and-threat-detection/database-auditing-and-threat-detection.sh
sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh
sql-database/failover-groups/add-managed-instance-to-failover-group-az-cli.sh
sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh
sql-database/import-from-bacpac/import-from-bacpac.sh
sql-database/managed-instance/create-managed-instance.sh
sql-database/monitor-and-scale-database/monitor-and-scale-database.sh
sql-database/move-database-between-pools/move-database-between-pools.sh
sql-database/restore-database/restore-database.sh
sql-database/scale-pool/scale-pool.sh

CLI version:
```
az --version
```

more consistency

---

sql-database/managed-instance/create-managed-instance.sh
sql-database/restore-database/restore-database.sh
sql-database/sql-managed-instance-restore-geo-backup/restore-geo-backup-cli.sh
sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.sh

CLI version:
```
az --version
```

bash comment

---

sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh

CLI version:
```
az --version
```

naming inconsistence

---

sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh
sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh

CLI version:
```
az --version
```

change echo language for a failover group

---

sql-database/create-and-configure-database/create-and-configure-database.sh
sql-database/failover-groups/add-managed-instance-to-failover-group-az-cli.sh
sql-database/managed-instance/create-managed-instance.sh

CLI version:
```
az --version
```

naming convention

---

sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh
sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-database-failover-group.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-elastic-pool.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-single-database.sh

CLI version:
```
az --version
```

failover server to secondary server

---

mariadb/backup-restore-pitr/backup-restore.sh
mariadb/backup-restore-pitr/delete-mariadb.sh
mariadb/change-server-configurations/change-server-configurations.sh
mariadb/change-server-configurations/delete-mariadb.sh
mariadb/create-mariadb-server-and-firewall-rule/create-mariadb-server-and-firewall-rule.sh
mariadb/create-mariadb-server-and-firewall-rule/delete-mariadb.sh
mariadb/create-mariadb-server-vnet/create-mariadb-server.sh
mariadb/create-mariadb-server-vnet/delete-mariadb.sh
mariadb/scale-mariadb-server/delete-mariadb.sh
mariadb/scale-mariadb-server/scale-mariadb-server.sh
mariadb/server-logs/delete-mariadb.sh
mariadb/server-logs/server-logs.sh

CLI version:
```
az --version
```

Azurecli mariadb

---

mariadb/backup-restore-pitr/delete-mariadb.sh
mariadb/change-server-configurations/delete-mariadb.sh
mariadb/create-mariadb-server-and-firewall-rule/delete-mariadb.sh
mariadb/create-mariadb-server-vnet/delete-mariadb.sh
mariadb/scale-mariadb-server/delete-mariadb.sh
mariadb/server-logs/delete-mariadb.sh

CLI version:
```
az --version
```

temporarily add back delete script

---

mariadb/backup-restore-pitr/backup-restore.sh
mariadb/change-server-configurations/change-server-configurations.sh
mariadb/create-mariadb-server-and-firewall-rule/create-mariadb-server-and-firewall-rule.sh
mariadb/create-mariadb-server-vnet/create-mariadb-server.sh
mariadb/scale-mariadb-server/scale-mariadb-server.sh
mariadb/server-logs/server-logs.sh

CLI version:
```
az --version
```

edits per Shreya

---

postgresql/backup-restore/backup-restore.sh
postgresql/change-server-configurations/change-server-configurations.sh
postgresql/create-postgresql-server-and-firewall-rule/create-postgresql-server-and-firewall-rule.sh
postgresql/create-postgresql-server-vnet/create-postgresql-server.sh
postgresql/scale-postgresql-server/scale-postgresql-server.sh
postgresql/server-logs/server-logs.sh

CLI version:
```
az --version
```

Azurecli postgresql

---

mariadb/backup-restore-pitr/delete-mariadb.sh
mariadb/change-server-configurations/delete-mariadb.sh
mariadb/create-mariadb-server-and-firewall-rule/delete-mariadb.sh
mariadb/create-mariadb-server-vnet/delete-mariadb.sh
mariadb/scale-mariadb-server/delete-mariadb.sh
mariadb/server-logs/delete-mariadb.sh

CLI version:
```
az --version
```

delete delete scripts as not used

---

postgresql/scale-postgresql-server/scale-postgresql-server.sh

CLI version:
```
az --version
```

remove comment

---

mariadb/scale-mariadb-server/scale-mariadb-server.sh

CLI version:
```
az --version
```

update subscriptionID variable definition

---

sql-database/create-and-configure-database/create-and-configure-database.sh
sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh
sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh

CLI version:
```
az --version
```

add file used in comment

---

postgresql/create-postgresql-server-and-firewall-rule/create-postgresql-server-and-firewall-rule.sh

CLI version:
```
az --version
```

add note re: script used in articles

---

media-services/create-asset/Create-Asset.sh

Good shell habit: leaving a space between the parameter and the "line continuation" backslash.
CLI version:
```
az --version
```
```
azure-cli                         2.32.0
core                              2.32.0
telemetry                          1.0.6
Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0
Python location '/opt/az/bin/python3'
Extensions directory '/home/ubuntu/.azure/cliextensions'
Python (Linux) 3.6.10 (default, Dec 31 2021, 08:09:22) 
[GCC 9.3.0]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.
```

media-services::Create-Asset.sh: leave a space between the parameter and the line continuation backslash

---

virtual-network/filter-network-traffic/filter-network-traffic.sh
virtual-network/peer-two-virtual-networks/peer-two-virtual-networks.sh
virtual-network/route-traffic-through-nva/route-traffic-through-nva.sh
virtual-network/virtual-network-cli-sample-ipv6-dual-stack-standard-load-balancer/virtual-network-cli-sample-ipv6-dual-stack-standard-load-balancer.sh
virtual-network/virtual-network-cli-sample-ipv6-dual-stack/virtual-network-cli-sample-ipv6-dual-stack.sh
virtual-network/virtual-network-multi-tier-application/virtual-network-multi-tier-application.sh

CLI version:
```
az --version
```

added 2 more scripts

---

virtual-network/virtual-network-cli-sample-ipv6-dual-stack-standard-load-balancer/virtual-network-cli-sample-ipv6-dual-stack-standard-load-balancer.sh
virtual-network/virtual-network-cli-sample-ipv6-dual-stack/virtual-network-cli-sample-ipv6-dual-stack.sh

CLI version:
```
az --version
```

fix important note

---

mysql/backup-restore-pitr/backup-restore.sh
mysql/flexible-server/backup-restore/restore-server.sh
mysql/flexible-server/create-server-public-access/create-connect-burstable-server-public-access.sh

CLI version:
```
az --version
```

update restore scripts

---

mariadb/backup-restore-pitr/backup-restore.sh
mysql/backup-restore-pitr/backup-restore.sh
mysql/flexible-server/backup-restore/restore-server.sh
postgresql/backup-restore/backup-restore.sh
sql-database/restore-database/restore-database.sh

CLI version:
```
az --version
```

update restore point variable

---

mariadb/backup-restore-pitr/backup-restore.sh
mysql/backup-restore-pitr/backup-restore.sh
mysql/flexible-server/backup-restore/restore-server.sh
postgresql/backup-restore/backup-restore.sh
sql-database/restore-database/restore-database.sh
sql-database/sql-managed-instance-restore-geo-backup/restore-geo-backup-cli.sh

CLI version:
```
az --version
```

fix extra space

---

mariadb/backup-restore-pitr/backup-restore.sh
mysql/flexible-server/create-server-public-access/create-connect-burstable-server-public-access.sh
postgresql/backup-restore/backup-restore.sh
sql-database/managed-instance/create-managed-instance.sh
sql-database/restore-database/restore-database.sh
sql-database/sql-managed-instance-restore-geo-backup/restore-geo-backup-cli.sh

CLI version:
```
az --version
```

update bash to cloud shell

---

postgresql/backup-restore/delete-postgresql.sh
postgresql/change-server-configurations/delete-postgresql.sh
postgresql/create-postgresql-server-and-firewall-rule/delete-postgresql.sh
postgresql/create-postgresql-server-vnet/delete-postgresql.sh
postgresql/scale-postgresql-server/delete-postgresql.sh
postgresql/server-logs/delete-postgresql.sh

CLI version:
```
az --version
```

delete postgresql delete scripts - not used

---

sql-database/restore-database/restore-database.sh
sql-database/sql-managed-instance-restore-geo-backup/restore-geo-backup-cli.sh

CLI version:
```
az --version
```

bash rather than cloud shell

---

mysql/flexible-server/manage-server/restart-start-stop.sh

CLI version:
```
az --version
```

fix script

---

cosmosdb/cassandra/autoscale.sh
cosmosdb/cassandra/create.sh
cosmosdb/cassandra/lock.sh
cosmosdb/cassandra/serverless.sh
cosmosdb/cassandra/throughput.sh
cosmosdb/common/ipfirewall.sh
cosmosdb/common/keys.sh
cosmosdb/common/regions.sh
cosmosdb/common/service-endpoints-ignore-missing-vnet.sh
cosmosdb/common/service-endpoints.sh
cosmosdb/gremlin/autoscale.sh
cosmosdb/gremlin/create.sh
cosmosdb/gremlin/lock.sh
cosmosdb/gremlin/serverless.sh
cosmosdb/gremlin/throughput.sh
cosmosdb/mongodb/autoscale.sh
cosmosdb/mongodb/create.sh
cosmosdb/mongodb/lock.sh
cosmosdb/mongodb/serverless.sh
cosmosdb/mongodb/throughput.sh
cosmosdb/sql/autoscale.sh
cosmosdb/sql/create.sh
cosmosdb/sql/lock.sh
cosmosdb/sql/serverless.sh
cosmosdb/sql/throughput.sh
cosmosdb/table/autoscale.sh
cosmosdb/table/create.sh
cosmosdb/table/lock.sh
cosmosdb/table/serverless.sh
cosmosdb/table/throughput.sh

CLI version:
```
az --version
```

Azurecli cosmosdb

---

cosmosdb/common/keys.sh

CLI version:
```
az --version
```

remove redundant information

---

mysql/flexible-server/create-server-private-access/create-connect-server-in-vnet.sh
mysql/flexible-server/create-server-public-access/create-connect-burstable-server-public-access.sh
mysql/flexible-server/high-availability/same-zone-ha.sh
mysql/flexible-server/high-availability/zone-redundant-ha.sh
mysql/flexible-server/manage-server/change-server-parameters.sh

CLI version:
```
az --version
```

per Shreya

---

cosmosdb/cassandra/throughput.sh
cosmosdb/gremlin/throughput.sh
cosmosdb/mongodb/throughput.sh
cosmosdb/sql/throughput.sh
cosmosdb/table/throughput.sh

CLI version:
```
az --version
```

spaces between lines

---

mysql/flexible-server/create-server-public-access/create-connect-burstable-server-public-access.sh

CLI version:
```
az --version
```

remove bash line

---

virtual-machine/create-vm-nlb/create-vm-nlb.sh
virtual-machine/create-vm-nlb/create-windows-vm-nlb.sh

CLI version:
```
az --version
```

restore temporarily deleted scripts-load balancer

---

cosmosdb/cassandra/autoscale.sh
cosmosdb/cassandra/create.sh
cosmosdb/cassandra/serverless.sh
cosmosdb/cassandra/throughput.sh
cosmosdb/gremlin/create.sh
cosmosdb/mongodb/create.sh
cosmosdb/mongodb/serverless.sh
cosmosdb/mongodb/throughput.sh
cosmosdb/sql/create.sh
cosmosdb/sql/serverless.sh

CLI version:
```
az --version
```

update uniqueId to random & fix comment

---

virtual-machine/copy-managed-disks-to-same-or-different-subscription/copy-managed-disks-to-same-or-different-subscription.sh
virtual-machine/copy-managed-disks-vhd-to-storage-account/copy-managed-disks-vhd-to-storage-account.sh
virtual-machine/copy-snapshot-to-same-or-different-subscription/copy-snapshot-to-same-or-different-subscription.sh
virtual-machine/copy-snapshots-to-storage-account/copy-snapshots-to-storage-account.sh
virtual-machine/create-managed-data-disks-from-vhd/create-managed-data-disks-from-vhd.sh
virtual-machine/create-managed-disks-from-snapshot/create-managed-disks-from-snapshot.sh
virtual-machine/create-vm-attach-existing-managed-os-disk/create-vm-attach-existing-managed-os-disk.sh
virtual-machine/create-vm-from-snapshot/create-vm-from-snapshot.sh

CLI version:
```
az --version
```

added date to file and remove actual subId

---

virtual-machine/copy-managed-disks-to-same-or-different-subscription/copy-managed-disks-to-same-or-different-subscription.sh
virtual-machine/copy-managed-disks-vhd-to-storage-account/copy-managed-disks-vhd-to-storage-account.sh
virtual-machine/copy-snapshot-to-same-or-different-subscription/copy-snapshot-to-same-or-different-subscription.sh
virtual-machine/copy-snapshots-to-storage-account/copy-snapshots-to-storage-account.sh
virtual-machine/create-managed-data-disks-from-vhd/create-managed-data-disks-from-vhd.sh
virtual-machine/create-managed-disks-from-snapshot/create-managed-disks-from-snapshot.sh
virtual-machine/create-vm-attach-existing-managed-os-disk/create-vm-attach-existing-managed-os-disk.sh
virtual-machine/create-vm-from-snapshot/create-vm-from-snapshot.sh

CLI version:
```
az --version
```

remove extra lines

---

traffic-manager/direct-traffic-for-increased-application-availability/direct-traffic-for-increased-application-availability.sh

CLI version:
```
az --version
```

update to CLI sample standards

---

storage/calculate-container-size/calculate-container-size.sh
storage/delete-containers-by-prefix/delete-containers-by-prefix.sh
storage/rotate-storage-account-keys/rotate-storage-account-keys.sh

CLI version:
```
az --version
```

Azurecli storage

---

storage/rotate-storage-account-keys/rotate-storage-account-keys.sh

CLI version:
```
az --version
```

fix line 4

---

managed-applications/create-application/create-managed-application.sh

CLI version:
```
az --version
```

Azurecli managed applications

---

virtual-network/create-nat-gateway/create-nat-gateway-cli.sh
virtual-network/filter-network-traffic/filter-network-traffic.sh
virtual-network/peer-two-virtual-networks/peer-two-virtual-networks.sh
virtual-network/route-traffic-through-nva/route-traffic-through-nva.sh
virtual-network/virtual-network-cli-sample-ipv6-dual-stack-standard-load-balancer/virtual-network-cli-sample-ipv6-dual-stack-standard-load-balancer.sh
virtual-network/virtual-network-cli-sample-ipv6-dual-stack/virtual-network-cli-sample-ipv6-dual-stack.sh
virtual-network/virtual-network-multi-tier-application/virtual-network-multi-tier-application.sh

CLI version:
```
az --version
```

Azurecli virtualnetwork

---

mariadb/backup-restore-pitr/backup-restore.sh
mariadb/change-server-configurations/change-server-configurations.sh
mariadb/create-mariadb-server-and-firewall-rule/create-mariadb-server-and-firewall-rule.sh
mariadb/create-mariadb-server-vnet/create-mariadb-server.sh
mariadb/scale-mariadb-server/scale-mariadb-server.sh
mariadb/server-logs/server-logs.sh

CLI version:
```
az --version
```

remove line returns

---

virtual-network/create-nat-gateway/create-nat-gateway-cli.sh
virtual-network/filter-network-traffic/filter-network-traffic.sh
virtual-network/peer-two-virtual-networks/peer-two-virtual-networks.sh
virtual-network/route-traffic-through-nva/route-traffic-through-nva.sh
virtual-network/virtual-network-cli-sample-ipv6-dual-stack-standard-load-balancer/virtual-network-cli-sample-ipv6-dual-stack-standard-load-balancer.sh
virtual-network/virtual-network-cli-sample-ipv6-dual-stack/virtual-network-cli-sample-ipv6-dual-stack.sh
virtual-network/virtual-network-multi-tier-application/virtual-network-multi-tier-application.sh

CLI version:
```
az --version
```

remove line return

---

traffic-manager/direct-traffic-for-increased-application-availability/direct-traffic-for-increased-application-availability.sh

CLI version:
```
az --version
```

add HTML tag

---

sql-database/backup-database/backup-database.sh
sql-database/copy-database-to-new-server/copy-database-to-new-server.sh
sql-database/create-and-configure-database/create-and-configure-database.sh
sql-database/database-auditing-and-threat-detection/database-auditing-and-threat-detection.sh
sql-database/failover-groups/add-elastic-pool-to-failover-group-az-cli.sh
sql-database/failover-groups/add-single-db-to-failover-group-az-cli.sh
sql-database/import-from-bacpac/import-from-bacpac.sh
sql-database/managed-instance/create-managed-instance.sh
sql-database/monitor-and-scale-database/monitor-and-scale-database.sh
sql-database/move-database-between-pools/move-database-between-pools.sh
sql-database/restore-database/restore-database.sh
sql-database/scale-pool/scale-pool.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-database-failover-group.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-elastic-pool.sh
sql-database/setup-geodr-and-failover/setup-geodr-and-failover-single-database.sh
sql-database/sql-managed-instance-restore-geo-backup/restore-geo-backup-cli.sh
sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.sh

CLI version:
```
az --version
```

add html block and more standardization

---

postgresql/create-postgresql-server-and-firewall-rule/create-postgresql-server-and-firewall-rule.sh

CLI version:
```
az --version
```

line return

---

mysql/backup-restore-pitr/backup-restore.sh
mysql/change-server-configurations/change-server-configurations.sh
mysql/create-mysql-server-and-firewall-rule/create-mysql-server-and-firewall-rule.sh
mysql/create-mysql-server-vnet/create-mysql-server.sh
mysql/flexible-server/backup-restore/restore-server.sh
mysql/flexible-server/configure-logs/configure-audit-logs.sh
mysql/flexible-server/configure-logs/configure-slow-query-logs.sh
mysql/flexible-server/create-server-private-access/create-connect-server-in-vnet.sh
mysql/flexible-server/create-server-public-access/create-connect-burstable-server-public-access.sh
mysql/flexible-server/high-availability/same-zone-ha.sh
mysql/flexible-server/high-availability/zone-redundant-ha.sh
mysql/flexible-server/manage-server/change-server-parameters.sh
mysql/flexible-server/manage-server/restart-start-stop.sh
mysql/flexible-server/monitor-and-scale/monitor-and-scale.sh
mysql/flexible-server/read-replicas/create-manage-read-replicas.sh
mysql/scale-mysql-server/scale-mysql-server.sh
mysql/server-logs/server-logs.sh

CLI version:
```
az --version
```

Html mysql

---

load-balancer/create-vm-nlb/create-vm-nlb.sh
load-balancer/load-balance-across-availability-zones/load-balance-across-availability-zones.sh
load-balancer/load-balance-multiple-web-sites-vm/load-balance-multiple-web-sites-vm.sh
load-balancer/load-balance-vms-within-specific-availability-zone/load-balance-vms-within-specific-availability-zone.sh

CLI version:
```
az --version
```

minor tidying up

---

managed-applications/create-application/create-managed-application.sh

CLI version:
```
az --version
```

remove extra line returns

---

cosmosdb/cassandra/autoscale.sh
cosmosdb/cassandra/create.sh
cosmosdb/cassandra/lock.sh
cosmosdb/cassandra/serverless.sh
cosmosdb/cassandra/throughput.sh
cosmosdb/common/ipfirewall.sh
cosmosdb/common/keys.sh
cosmosdb/common/regions.sh
cosmosdb/common/service-endpoints-ignore-missing-vnet.sh
cosmosdb/common/service-endpoints.sh
cosmosdb/gremlin/autoscale.sh
cosmosdb/gremlin/create.sh
cosmosdb/gremlin/lock.sh
cosmosdb/gremlin/serverless.sh
cosmosdb/gremlin/throughput.sh
cosmosdb/mongodb/autoscale.sh
cosmosdb/mongodb/create.sh
cosmosdb/mongodb/lock.sh
cosmosdb/mongodb/serverless.sh
cosmosdb/mongodb/throughput.sh
cosmosdb/sql/autoscale.sh
cosmosdb/sql/create.sh
cosmosdb/sql/lock.sh
cosmosdb/sql/serverless.sh
cosmosdb/sql/throughput.sh
cosmosdb/table/autoscale.sh
cosmosdb/table/create.sh
cosmosdb/table/lock.sh
cosmosdb/table/serverless.sh
cosmosdb/table/throughput.sh

CLI version:
```
az --version
```

add html block

---

virtual-machine/create-vm-quick/create-vm-quick.sh
virtual-machine/create-vm-quick/create-windows-vm-quick.sh

CLI version:
```
az --version
```

restore 2 files

---

azure-functions/deploy-function-app-with-function-github-continuous/deploy-function-app-with-function-github-continuous.sh

The line
```
az storage account create --name $storage --location "$location" --resource-group $resourceGroup --sku $skuStorage
```
refences a `$skuStorage` variable and the `az storage account create` requires a storage type to be set. Without setting `$skuStorage` the script throws an error `argument --sku: expected one argument` when trying to create the storage account.
I believe `skuStorage=Standard_LRS` is missing from the variables declaration block at the start of the script. (It's in the other scripts.)
~~`tags="deploy-function-app-with-function-github"` is also decalred but never used. The other sample scripts use it in `az group create`.~~
See #422 
CLI version: 2.34.1
```
az --version
```

Add missing skuStorage declaration and add tag to group create.

---

azure-signalr/create-signalr-service-and-group/create-signalr-service-and-group.sh
azure-signalr/create-signalr-with-app-service/create-signalr-with-app-service.sh

CLI version:
```
az --version
```

upate and standardize scripts

---

container-registry/create-registry/create-registry-service-principal-assign-role.sh
container-registry/service-principal-create/service-principal-create.sh

CLI version:
```
az --version
```

Azurecli container registry - update standardize variable html block combine

---

app-service/deploy-ftp/deploy-ftp.sh
app-service/deploy-github/deploy-github.sh

CLI version:
```
az --version
```

first 2 files

---

app-service/deploy-linux-docker/deploy-linux-docker-app-only.sh

CLI version:
```
az --version
```

docker web app only

---

app-service/connect-to-redis/connect-to-redis.sh
app-service/connect-to-sql/connect-to-sql.sh

CLI version:
```
az --version
```

two more scripts updated

---

app-service/connect-to-storage/connect-to-storage.sh

CLI version:
```
az --version
```

one more script

---

app-service/deploy-vsts-continuous/deploy-vsts-continuous-webapp-only.sh

CLI version:
```
az --version
```

vsts continuous updated script

---

app-service/integrate-with-app-gateway/integrate-with-app-gateway.sh
app-service/monitor-with-logs/monitor-with-logs.sh
app-service/scale-geographic/scale-geographic.sh
app-service/scale-manual/scale-manual.sh

CLI version:
```
az --version
```

more upated scripts

---

app-service/integrate-with-app-gateway/integrate-with-app-gateway.sh

CLI version:
```
az --version
```

one more fix

---

app-service/connect-to-redis/connect-to-redis.sh
app-service/connect-to-storage/connect-to-storage.sh
app-service/deploy-ftp/deploy-ftp.sh
app-service/deploy-github/deploy-github.sh
app-service/deploy-linux-docker/deploy-linux-docker-webapp-only.sh
app-service/deploy-vsts-continuous/deploy-vsts-continuous-webapp-only.sh
app-service/integrate-with-app-gateway/integrate-with-app-gateway.sh

CLI version:
```
az --version
```

retested all scripts

---

app-service/deploy-linux-docker/deploy-linux-docker-webapp-only.sh

CLI version:
```
az --version
```

fixed docker script

---

app-service/backup-one-time-schedule-restore/backup-restore.sh
app-service/configure-custom-domain/configure-custom-domain-webapp-only.sh
app-service/configure-ssl-certificate/configure-ssl-certificate-webapp-only.sh
app-service/connect-to-documentdb/connect-to-documentdb.sh
app-service/connect-to-redis/connect-to-redis.sh
app-service/connect-to-sql/connect-to-sql.sh
app-service/connect-to-storage/connect-to-storage.sh
app-service/deploy-deployment-slot/deploy-deployment-slot.sh
app-service/deploy-ftp/deploy-ftp.sh
app-service/deploy-github/deploy-github.sh
app-service/deploy-linux-docker/deploy-linux-docker-webapp-only.sh
app-service/deploy-vsts-continuous/deploy-vsts-continuous-webapp-only.sh
app-service/integrate-with-app-gateway/integrate-with-app-gateway.sh
app-service/monitor-with-logs/monitor-with-logs.sh
app-service/scale-geographic/scale-geographic.sh
app-service/scale-manual/scale-manual.sh

CLI version:
```
az --version
```

cleanup and one more script

---

app-service/backup-one-time-schedule-restore/backup-restore.sh
app-service/configure-custom-domain/configure-custom-domain-webapp-only.sh
app-service/configure-ssl-certificate/configure-ssl-certificate-webapp-only.sh
app-service/connect-to-documentdb/connect-to-documentdb.sh
app-service/connect-to-redis/connect-to-redis.sh
app-service/connect-to-sql/connect-to-sql.sh
app-service/connect-to-storage/connect-to-storage.sh
app-service/deploy-deployment-slot/deploy-deployment-slot.sh
app-service/deploy-ftp/deploy-ftp.sh
app-service/deploy-github/deploy-github.sh
app-service/deploy-linux-docker/deploy-linux-docker-webapp-only.sh
app-service/deploy-vsts-continuous/deploy-vsts-continuous-webapp-only.sh
app-service/integrate-with-app-gateway/integrate-with-app-gateway.sh
app-service/monitor-with-logs/monitor-with-logs.sh
app-service/scale-geographic/scale-geographic.sh
app-service/scale-manual/scale-manual.sh

CLI version:
```
az --version
```

re-order steps

---

container-instances/nat-gateway.sh

CLI version:
```
az --version
```

new file for code blocks

---

container-instances/nat-gateway.sh

CLI version:
```
az --version
```

fixed missing bracket

---

container-instances/egress-ip-address.sh

CLI version:
```
az --version
```

fix typos in html

---

azure-monitor/log-analytics.sh

CLI version:
```
az --version
```

new file from code blocks

---

azure-functions/functions-cli-mount-files-storage-linux/functions-cli-mount-files-storage-linux.sh

Fix typo msdcos -> msdocs
CLI version:
```
az --version
```

Fix typo msdcos -> msdocs

---

azure-functions/create-function-app-connect-to-cosmos-db/create-function-app-connect-to-cosmos-db.sh

Add a missing storage variable.
CLI version:
```
az --version
```

Fix a typo

---

.github/workflows/test-deploy.yml
azure-front-door/deploy-custom-domain/deploy-custom-domain.sh

CLI version:
```
az --version
```

Azure actions

---

batch/add-application/add-application.sh
batch/manage-pool/manage-pool-linux.sh
batch/manage-pool/manage-pool-windows.sh
batch/run-job/run-job.sh

CLI version:
```
az --version
```

updated script description

---

app-service/integrate-with-app-gateway/integrate-with-app-gateway.sh

A change in the app gateway API now requires priority to be defined. Reported here https://github.com/MicrosoftDocs/azure-docs/issues/97622
CLI version:
```
az --version
```

Fix missing priority

---

redis-cache/create-cache/create-manage-cache.sh

CLI version:
```
az --version
```

fxl---Fixed typos in script

---

virtual-machine/create-vm-from-snapshot/create-vm-from-snapshot.sh

CLI version:
```
az --version
```

Removing typo

---

virtual-machine/create-managed-disks-from-snapshot/create-managed-disks-from-snapshot.sh

CLI version:
```
az --version
```

Updating script to accommodate Premium SSD v2 and Ultra Disks.

---

README.md

CLI version:
```
az --version
```

Update repository README.md

---

app-service/README.md

CLI version:
```
az --version
```

Create Azure Container Registry README.md

---

app-service/README.md

CLI version:
```
az --version
```

Update app-service primary README.md

---

virtual-machine/create-managed-data-disks-from-vhd/create-managed-data-disks-from-vhd.sh

CLI version:
```
az --version
```

Adding optional parameters for OS disks

---

azure-cli/create-azure-resources-at-scale/bash/create-azure-resources-at-scale.sh

CLI version:
```
az --version
```

Creating framework for creating resources at scale files

---

.github/pull_request_template.md
app-service/README.md
azure-front-door/deploy-custom-domain/README.md
sql-database/sql-managed-instance-restore-geo-backup/restore-geo-backup-cli.sh
sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.sh
virtual-machine/copy-managed-disks-vhd-to-storage-account/copy-managed-disks-vhd-to-storage-account.sh
virtual-machine/copy-snapshot-to-same-or-different-subscription/copy-snapshot-to-same-or-different-subscription.sh
virtual-machine/copy-snapshots-to-storage-account/copy-snapshots-to-storage-account.sh

CLI version:
```
az --version
```

removing /en-us/ from links

---

azure-cli/create-azure-resources-at-scale/bash/create-azure-resources-at-scale.sh
azure-cli/create-azure-resources-at-scale/create-azure-resources-at-scale-metadata.csv
azure-cli/create-azure-resources-at-scale/powershell/create-azure-resources-at-scale.ps1

CLI version:
```
az --version
```

create resources at scale | testing improvements and more log reporting

---

cosmosdb/common/convert-to-autoscale.sh

just adding this to end of script, # </FullScript>

add end full script tag
